###
# @Author: 3812943352 168046603+3812943352@users.noreply.github.com
# @Date: 2025-03-12 11:02:26
# @LastEditors: 3812943352 168046603+3812943352@users.noreply.github.com
# @LastEditTime: 2025-03-14 08:50:58
# @FilePath: user-service/src/main/resources/application.yml
# @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
###

spring:
  application:
    name: user-service
  config:
    import: nacos:user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: c0331mgf
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        username: nacos
        password: c0331mgf