###
# @Author: 3812943352 168046603+3812943352@users.noreply.github.com
# @Date: 2025-03-19 22:37:08
# @LastEditors: 3812943352 168046603+3812943352@users.noreply.github.com
# @LastEditTime: 2025-04-02 19:20:42
# @FilePath: order-service/src/main/resources/application.yml
# @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
###
###
# @Author: 3812943352 168046603+3812943352@users.noreply.github.com
# @Date: 2025-03-13 22:26:43
# @LastEditors: 3812943352 168046603+3812943352@users.noreply.github.com
# @LastEditTime: 2025-03-14 09:37:47
# @FilePath: order-service/src/main/resources/application.yml
# @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
###
###
# @Author: 3812943352 168046603+3812943352@users.noreply.github.com
# @Date: 2025-03-13 22:26:43
# @LastEditors: 3812943352 168046603+3812943352@users.noreply.github.com
# @LastEditTime: 2025-03-14 09:00:01
# @FilePath: order-service/src/main/resources/application.yml
# @Description: 这是默认设置,可以在设置》工具》File Description中进行配置
###
spring:
  application:
    name: order-service
  config:
    import: nacos:order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: c0331mgf
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        username: nacos
        password: c0331mgf